version = 1

test_patterns = [
  "**/*_test.go"
]

exclude_patterns = [
  ".gen/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/uber/cadence"

[[analyzers]]
name = "docker"
enabled = true
